# Generated by Django 3.2 on 2022-02-28 23:16

from django.conf import settings
import django.contrib.postgres.operations
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('rates', '0001_initial'), ('rates', '0002_ratesinvitation'), ('rates', '0003_auto_20211115_2020'), ('rates', '0004_auto_20211214_1311'), ('rates', '0005_auto_20211218_2238'), ('rates', '0006_auto_20211218_2242'), ('rates', '0007_auto_20211218_2244'), ('rates', '0008_auto_20211223_1526'), ('rates', '0009_auto_20220109_1907'), ('rates', '0010_alter_ratereport_negotiated'), ('rates', '0011_contact'), ('rates', '0012_auto_20220206_2056'), ('rates', '0013_auto_20220207_1143'), ('rates', '0014_auto_20220207_1204'), ('rates', 'trigram_migration'), ('rates', '0001_auto_20220207_1559'), ('rates', '0002_auto_20220208_1344'), ('rates', '0003_rawratereport_user_created_values'), ('rates', '0004_auto_20220209_1211'), ('rates', '0005_alter_ratereport_raw_report'), ('rates', '0006_auto_20220210_1013'), ('rates', '0007_auto_20220210_1027')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('invitations', '0004_alter_invitation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128)),
                ('long_name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('union', models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=4, null=True)),
                ('genre', models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game Show'), ('LI', 'Live Show'), ('TA', 'Talk Show'), ('JU', 'Judge Show'), ('OT', 'Other Unscripted'), ('SC', 'Scripted')], max_length=4, null=True)),
                ('companies', models.ManyToManyField(blank=True, to='rates.Company')),
                ('locations', models.ManyToManyField(blank=True, related_name='locations', to='rates.Location')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.network')),
                ('scopes', models.ManyToManyField(blank=True, related_name='scopes', to='rates.Location')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.show')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36)),
                ('job_title_name', models.CharField(max_length=128)),
                ('offered_hourly', models.DecimalField(decimal_places=4, max_digits=9)),
                ('show', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36)),
                ('show_title', models.CharField(max_length=128)),
                ('season_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('companies', models.JSONField(blank=True, null=True)),
                ('network', models.CharField(max_length=36, null=True)),
                ('network_name', models.CharField(blank=True, max_length=128, null=True)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('union', models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=4, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game Show'), ('LI', 'Live Show'), ('TA', 'Talk Show'), ('JU', 'Judge Show'), ('OT', 'Other Unscripted'), ('SC', 'Scripted')], max_length=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('final_guarantee', models.PositiveSmallIntegerField(null=True)),
                ('final_hourly', models.DecimalField(decimal_places=4, max_digits=9, null=True)),
                ('increased', models.BooleanField(null=True)),
                ('negotiated', models.BooleanField(default=False)),
                ('offered_guarantee', models.PositiveSmallIntegerField(default=8)),
                ('company_matches', models.ManyToManyField(null=True, related_name='company_matches', to='rates.Company')),
                ('job_title_matches', models.ManyToManyField(null=True, related_name='job_title_matches', to='rates.JobTitle')),
                ('network_matches', models.ManyToManyField(null=True, related_name='network_matches', to='rates.Network')),
                ('show_matches', models.ManyToManyField(null=True, related_name='show_matches', to='rates.Show')),
            ],
        ),
        migrations.CreateModel(
            name='RatesInvitation',
            fields=[
                ('invitation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invitations.invitation')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('invitations.invitation',),
        ),
        migrations.CreateModel(
            name='RateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_hourly', models.DecimalField(decimal_places=4, max_digits=9)),
                ('offered_guarantee', models.PositiveSmallIntegerField()),
                ('union', models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=4, null=True)),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.jobtitle')),
                ('raw_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.rawratereport')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.season')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('final_guarantee', models.PositiveSmallIntegerField(null=True)),
                ('final_hourly', models.DecimalField(decimal_places=4, max_digits=9, null=True)),
                ('increased', models.BooleanField(null=True)),
                ('negotiated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=512)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        django.contrib.postgres.operations.TrigramExtension(
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='final_guarantee',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='final_hourly',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='genre',
            field=models.CharField(blank=True, choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game Show'), ('LI', 'Live Show'), ('TA', 'Talk Show'), ('JU', 'Judge Show'), ('OT', 'Other Unscripted'), ('SC', 'Scripted')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='increased',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='network',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='union',
            field=models.CharField(blank=True, choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=4, null=True),
        ),
        migrations.RenameField(
            model_name='ratesinvitation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='ratesinvitation',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ratesinvitation',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='user_created_values',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratereport',
            name='percent_increase',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratereport',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ratereport',
            name='raw_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.rawratereport'),
        ),
        migrations.AddField(
            model_name='ratereport',
            name='offered_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='offered_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratereport',
            name='final_daily',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='final_daily',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
