# Generated by Django 3.2 on 2022-02-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', 'trigram_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawratereport',
            name='final_guarantee',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='final_hourly',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='genre',
            field=models.CharField(blank=True, choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game Show'), ('LI', 'Live Show'), ('TA', 'Talk Show'), ('JU', 'Judge Show'), ('OT', 'Other Unscripted'), ('SC', 'Scripted')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='increased',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='network',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='union',
            field=models.CharField(blank=True, choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=4, null=True),
        ),
    ]
