# Generated by Django 3.2 on 2021-05-15 04:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128)),
                ('long_name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('union', models.BooleanField()),
                ('genre', models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game'), ('LI', 'Live'), ('TA', 'Talk'), ('JU', 'Judge')], default='RE', max_length=2)),
                ('companies', models.ManyToManyField(blank=True, to='rates.company')),
                ('locations', models.ManyToManyField(blank=True, related_name='locations', to='rates.Location')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.network')),
                ('scopes', models.ManyToManyField(blank=True, related_name='scopes', to='rates.Location')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.show')),
            ],
        ),
        migrations.CreateModel(
            name='RawRateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title_id', models.SmallIntegerField()),
                ('job_title_name', models.CharField(max_length=128)),
                ('hourly', models.DecimalField(decimal_places=4, max_digits=9)),
                ('guarantee', models.PositiveSmallIntegerField()),
                ('show_id', models.SmallIntegerField()),
                ('show_title', models.CharField(max_length=128)),
                ('season_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('company_id', models.SmallIntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=128)),
                ('network_id', models.SmallIntegerField(blank=True, null=True)),
                ('network_name', models.CharField(blank=True, max_length=128)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('union', models.BooleanField()),
                ('approved', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game'), ('LI', 'Live'), ('TA', 'Talk'), ('JU', 'Judge')], default='RE', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly', models.DecimalField(decimal_places=4, max_digits=9)),
                ('guarantee', models.PositiveSmallIntegerField()),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.jobtitle')),
                ('raw_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.rawratereport')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.season')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
