# Generated by Django 3.2 on 2022-02-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_auto_20220207_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratesinvitation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='ratesinvitation',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ratesinvitation',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='first_name',
        #     field=models.CharField(blank=True, max_length=128, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='last_name',
        #     field=models.CharField(blank=True, max_length=128, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='preferred_name',
        #     field=models.CharField(blank=True, max_length=128, null=True),
        # ),
    ]
