# Generated by Django 3.2 on 2021-05-14 22:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128)),
                ('long_name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('union', models.BooleanField()),
                ('genre', models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game'), ('LI', 'Live'), ('TA', 'Talk')], default='RE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonsScopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.location')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.season')),
            ],
            options={
                'db_table': 'rates_seasons_scopes',
            },
        ),
        migrations.CreateModel(
            name='SeasonsLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.location')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.season')),
            ],
            options={
                'db_table': 'rates_seasons_locations',
            },
        ),
        migrations.CreateModel(
            name='SeasonsCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.company')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.season')),
            ],
            options={
                'db_table': 'rates_seasons_companies',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='company',
            field=models.ManyToManyField(blank=True, through='rates.SeasonsCompanies', to='rates.Company'),
        ),
        migrations.AddField(
            model_name='season',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='locations', through='rates.SeasonsLocations', to='rates.Location'),
        ),
        migrations.AddField(
            model_name='season',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.network'),
        ),
        migrations.AddField(
            model_name='season',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='scopes', through='rates.SeasonsScopes', to='rates.Location'),
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.show'),
        ),
        migrations.CreateModel(
            name='RawRateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title_id', models.SmallIntegerField()),
                ('job_title_name', models.CharField(max_length=128)),
                ('hourly', models.DecimalField(decimal_places=4, max_digits=9)),
                ('guarantee', models.PositiveSmallIntegerField()),
                ('show_id', models.SmallIntegerField()),
                ('show_title', models.CharField(max_length=128)),
                ('season_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('company_id', models.SmallIntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=128)),
                ('network_id', models.SmallIntegerField(blank=True, null=True)),
                ('network_name', models.CharField(blank=True, max_length=128)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('union', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly', models.DecimalField(decimal_places=4, max_digits=9)),
                ('guarantee', models.PositiveSmallIntegerField()),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.jobtitle')),
                ('raw_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.rawratereport')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.season')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
