# Generated by Django 3.2 on 2021-05-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_company_jobtitle_location_network_ratereport_rawratereport_season_show_02'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratereport',
            name='union',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='companies',
            field=models.ManyToManyField(blank=True, to='rates.Company'),
        ),
    ]
