# Generated by Django 3.2 on 2022-02-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_auto_20220208_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawratereport',
            name='user_created_values',
            field=models.BooleanField(default=False),
        ),
    ]
