# Generated by Django 3.2 on 2021-05-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_auto_20210514_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawratereport',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
