# Generated by Django 3.2 on 2022-02-09 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_rawratereport_user_created_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratereport',
            name='percent_increase',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratereport',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
