# Generated by Django 3.2 on 2021-05-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_auto_20210515_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratereport',
            name='union',
            field=models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='union',
            field=models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='season',
            name='companies',
            field=models.ManyToManyField(blank=True, to='rates.Company'),
        ),
        migrations.AlterField(
            model_name='season',
            name='union',
            field=models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], default='NO', max_length=2),
        ),
    ]
