# Generated by Django 3.2 on 2021-12-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_auto_20211214_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratereport',
            name='union',
            field=models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='genre',
            field=models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game Show'), ('LI', 'Live Show'), ('TA', 'Talk Show'), ('JU', 'Judge Show'), ('OT', 'Other Unscripted'), ('SC', 'Scripted')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='job_title',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='show',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='union',
            field=models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=2),
        ),
        migrations.AlterField(
            model_name='season',
            name='genre',
            field=models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game Show'), ('LI', 'Live Show'), ('TA', 'Talk Show'), ('JU', 'Judge Show'), ('OT', 'Other Unscripted'), ('SC', 'Scripted')], max_length=2),
        ),
        migrations.AlterField(
            model_name='season',
            name='union',
            field=models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=2),
        ),
    ]
