# Generated by Django 3.2 on 2021-05-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_auto_20210516_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawratereport',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='rawratereport',
            name='company_name',
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='companies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='companies',
            field=models.ManyToManyField(blank=True, to='rates.Company'),
        ),
    ]
