# Generated by Django 3.2 on 2021-05-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_rawratereport_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawratereport',
            name='genre',
            field=models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game'), ('LI', 'Live'), ('TA', 'Talk'), ('JU', 'Judge')], default='RE', max_length=2),
        ),
        migrations.AlterField(
            model_name='season',
            name='genre',
            field=models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game'), ('LI', 'Live'), ('TA', 'Talk'), ('JU', 'Judge')], default='RE', max_length=2),
        ),
    ]
