# Generated by Django 3.2 on 2021-05-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_auto_20210516_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawratereport',
            old_name='job_title_id',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='rawratereport',
            old_name='network_id',
            new_name='network',
        ),
        migrations.RenameField(
            model_name='rawratereport',
            old_name='show_id',
            new_name='show',
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='genre',
            field=models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game Show'), ('LI', 'Live Show'), ('TA', 'Talk Show'), ('JU', 'Judge Show'), ('OT', 'Other Unscripted'), ('SC', 'Scripted')], default='RE', max_length=2),
        ),
        migrations.AlterField(
            model_name='season',
            name='companies',
            field=models.ManyToManyField(blank=True, to='rates.Company'),
        ),
        migrations.AlterField(
            model_name='season',
            name='genre',
            field=models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game Show'), ('LI', 'Live Show'), ('TA', 'Talk Show'), ('JU', 'Judge Show'), ('OT', 'Other Unscripted'), ('SC', 'Scripted')], default='RE', max_length=2),
        ),
    ]
