# Generated by Django 3.2 on 2022-02-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_alter_ratereport_raw_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratereport',
            name='final_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratereport',
            name='offered_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='final_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='offered_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
