# Generated by Django 3.2 on 2021-12-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_auto_20211218_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratereport',
            name='union',
            field=models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='genre',
            field=models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game Show'), ('LI', 'Live Show'), ('TA', 'Talk Show'), ('JU', 'Judge Show'), ('OT', 'Other Unscripted'), ('SC', 'Scripted')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='union',
            field=models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='genre',
            field=models.CharField(choices=[('RE', 'Reality'), ('DO', 'Documentary'), ('GA', 'Game Show'), ('LI', 'Live Show'), ('TA', 'Talk Show'), ('JU', 'Judge Show'), ('OT', 'Other Unscripted'), ('SC', 'Scripted')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='union',
            field=models.CharField(choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=2, null=True),
        ),
    ]
