# Generated by Django 3.2 on 2021-05-17 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_auto_20210516_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawratereport',
            name='guarantee',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='season',
            name='companies',
            field=models.ManyToManyField(blank=True, to='rates.Company'),
        ),
    ]
