# Generated by Django 3.2 on 2022-02-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_auto_20220210_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratereport',
            name='final_daily',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='final_daily',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
