# Generated by Django 3.2 on 2022-03-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_auto_20220210_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='unknown', max_length=512),
            preserve_default=False,
        ),
    ]
