# Generated by Django 3.2 on 2022-01-10 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0008_auto_20211223_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratereport',
            old_name='guarantee',
            new_name='offered_guarantee',
        ),
        migrations.RenameField(
            model_name='ratereport',
            old_name='hourly',
            new_name='offered_hourly',
        ),
        migrations.RenameField(
            model_name='rawratereport',
            old_name='hourly',
            new_name='offered_hourly',
        ),
        migrations.RemoveField(
            model_name='rawratereport',
            name='guarantee',
        ),
        migrations.AddField(
            model_name='ratereport',
            name='final_guarantee',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ratereport',
            name='final_hourly',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ratereport',
            name='increased',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ratereport',
            name='negotiated',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='final_guarantee',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='final_hourly',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='increased',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='negotiated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='offered_guarantee',
            field=models.PositiveSmallIntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='network_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
