# Generated by Django 3.2 on 2022-03-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0008_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratereport',
            name='final_hourly',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ratereport',
            name='union',
            field=models.CharField(blank=True, choices=[('NO', 'Non-Union'), ('IA', 'IATSE'), ('NA', 'NABET')], max_length=4, null=True),
        ),
    ]
