# Generated by Django 3.2 on 2021-05-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0008_auto_20210517_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='companies',
            field=models.ManyToManyField(blank=True, to='rates.Company'),
        ),
    ]
