# Generated by Django 3.2 on 2022-03-09 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0009_auto_20220306_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
