# Generated by Django 3.2 on 2021-10-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_invitation_id'),
        ('rates', '0009_alter_season_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatesInvitation',
            fields=[
                ('invitation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invitations.invitation')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('invitations.invitation',),
        ),
        migrations.AlterField(
            model_name='season',
            name='companies',
            field=models.ManyToManyField(blank=True, to='rates.Company'),
        ),
    ]
