# Generated by Django 3.2 on 2022-02-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0010_alter_ratereport_negotiated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=512)),
                ('message', models.TextField()),
            ],
        ),
    ]
