# Generated by Django 3.2.12 on 2022-03-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0010_season_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawratereport',
            name='company_matches',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_matches', to='rates.Company'),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='network_matches',
            field=models.ManyToManyField(blank=True, null=True, related_name='network_matches', to='rates.Network'),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='show_matches',
            field=models.ManyToManyField(blank=True, null=True, related_name='show_matches', to='rates.Show'),
        ),
    ]
