# Generated by Django 3.2.12 on 2022-03-29 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0012_alter_rawratereport_job_title_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawratereport',
            name='companies_override',
            field=models.ManyToManyField(blank=True, null=True, to='rates.Company'),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='job_title_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.jobtitle'),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='network_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.network'),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='show_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.show'),
        ),
    ]
