# Generated by Django 3.2 on 2022-02-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0012_auto_20220206_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawratereport',
            name='company_matches',
            field=models.ManyToManyField(related_name='company_matches', to='rates.Company'),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='job_title_matches',
            field=models.ManyToManyField(related_name='job_title_matches', to='rates.JobTitle'),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='network_matches',
            field=models.ManyToManyField(related_name='network_matches', to='rates.Network'),
        ),
        migrations.AddField(
            model_name='rawratereport',
            name='show_matches',
            field=models.ManyToManyField(related_name='show_matches', to='rates.Show'),
        ),
    ]
