# Generated by Django 3.2 on 2022-02-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0013_auto_20220207_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawratereport',
            name='company_matches',
            field=models.ManyToManyField(null=True, related_name='company_matches', to='rates.Company'),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='job_title_matches',
            field=models.ManyToManyField(null=True, related_name='job_title_matches', to='rates.JobTitle'),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='network_matches',
            field=models.ManyToManyField(null=True, related_name='network_matches', to='rates.Network'),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='show_matches',
            field=models.ManyToManyField(null=True, related_name='show_matches', to='rates.Show'),
        ),
    ]
