# Generated by Django 3.2.12 on 2022-03-29 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0013_auto_20220329_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawratereport',
            name='companies_override',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies_override', to='rates.Company'),
        ),
        migrations.AlterField(
            model_name='rawratereport',
            name='network_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_override', to='rates.network'),
        ),
    ]
